'use client'

import { useState, useRef, useEffect } from 'react'
import Link from 'next/link'
import {
  ArrowLeft, Send, Loader2, Cpu, AlertCircle, Settings,
  Zap, Copy, Check, Trash2, FileText, ChevronDown, ChevronUp, Printer,
} from 'lucide-react'
import OperativeSettings from '@/components/OperativeSettings'
import OperativeWizard from '@/components/OperativeWizard'
import UpgradeButton from '@/components/UpgradeButton'

interface Message {
  id: string
  role: 'user' | 'assistant'
  content: string
}

interface Output {
  id: string
  title: string
  content: string
  prompt?: string
  created_at: string
}

interface OperativeConfig {
  system_prompt?: string
  description?: string
}

interface Operative {
  id: string
  name: string
  suite_id: string
  status: string
  config: OperativeConfig
  created_at: string
  memory?: string
}

// Generate contextual quick actions from operative name/description
function getQuickActions(name: string, description: string): string[] {
  const text = (name + ' ' + description).toLowerCase()

  if (text.includes('pressure') || text.includes('wash') || text.includes('clean')) {
    return [
      'Write a quote for a residential driveway and house wash',
      'Write a 3-touch follow-up sequence for a lead that went cold',
      'Write a commercial property quote request response',
      'Write a bundle upsell message for an existing customer',
    ]
  }
  if (text.includes('landscap') || text.includes('lawn') || text.includes('mow')) {
    return [
      'Write a recurring maintenance contract proposal',
      'Write a spring cleanup upsell email to existing clients',
      'Write a commercial property bid package',
      'Write a follow-up for a quote sent 5 days ago with no response',
    ]
  }
  if (text.includes('hvac') || text.includes('plumb') || text.includes('electric') || text.includes('roof')) {
    return [
      'Write a service call estimate with parts and labor breakdown',
      'Write a maintenance plan proposal for a residential client',
      'Write a follow-up for a quote that went cold',
      'Write an emergency service response script',
    ]
  }
  if (text.includes('real estate') || text.includes('wholesale') || text.includes('invest')) {
    return [
      'Write an offer letter for a motivated seller',
      'Write a follow-up sequence for a cold lead property owner',
      'Write a disposition email to my buyers list',
      'Write a skip trace outreach message',
    ]
  }
  if (text.includes('recruit') || text.includes('staff') || text.includes('hire')) {
    return [
      'Write a candidate outreach email for an open role',
      'Write a job description for a client',
      'Write a client staffing proposal',
      'Write an interview prep document for a candidate',
    ]
  }
  if (text.includes('agency') || text.includes('market') || text.includes('creative')) {
    return [
      'Write a new client proposal with scope and pricing',
      'Write a monthly report for a client',
      'Write a client onboarding welcome sequence',
      'Write a cold outreach email to a prospect',
    ]
  }
  // Generic fallback
  return [
    'Write a professional quote for a new client',
    'Write a 3-touch follow-up for a cold lead',
    'Write a new client welcome and onboarding email',
    'Write a proposal for a large project or contract',
  ]
}

function printOutput(title: string, content: string) {
  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(`<!DOCTYPE html>
<html>
<head>
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Georgia, 'Times New Roman', serif; font-size: 13px; line-height: 1.7; color: #1a1a1a; padding: 60px 72px; max-width: 800px; margin: 0 auto; }
    h1 { font-size: 22px; font-weight: 700; margin-bottom: 4px; }
    h2 { font-size: 16px; font-weight: 700; margin: 24px 0 8px; }
    h3 { font-size: 14px; font-weight: 700; margin: 16px 0 6px; }
    p { margin: 8px 0; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; }
    th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; font-size: 12px; }
    th { background: #f5f5f5; font-weight: 700; }
    ul, ol { padding-left: 20px; margin: 8px 0; }
    li { margin: 4px 0; }
    hr { border: none; border-top: 1px solid #ddd; margin: 20px 0; }
    strong, b { font-weight: 700; }
    em, i { font-style: italic; }
    .header { border-bottom: 2px solid #1a1a1a; padding-bottom: 16px; margin-bottom: 24px; }
    .footer { border-top: 1px solid #ddd; margin-top: 40px; padding-top: 12px; font-size: 11px; color: #888; }
    @media print { body { padding: 40px 48px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    <p style="color:#888;font-size:11px;margin-top:4px;">Generated by Iron Operative · ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
  </div>
  <div id="content"></div>
  <div class="footer">AI-generated content. Review before use. Iron Operative — ironoperative.com</div>
  <script>
    const raw = ${JSON.stringify(content)};
    // Convert markdown-ish to HTML
    const html = raw
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/\\*\\*(.+?)\\*\\*/g, '<strong>$1</strong>')
      .replace(/\\*(.+?)\\*/g, '<em>$1</em>')
      .replace(/^---$/gm, '<hr>')
      .replace(/^\\| (.+)$/gm, (m) => {
        const cells = m.split('|').filter(c => c.trim() && !c.match(/^[-\\s]+$/));
        if (!cells.length) return '';
        return '<tr>' + cells.map(c => '<td>' + c.trim() + '</td>').join('') + '</tr>';
      })
      .replace(/(<tr>.*<\\/tr>\\n?)+/gs, (t) => '<table>' + t + '</table>')
      .replace(/^- (.+)$/gm, '<li>$1</li>')
      .replace(/(<li>.*<\\/li>\\n?)+/gs, (l) => '<ul>' + l + '</ul>')
      .replace(/\\n\\n/g, '</p><p>')
      .replace(/\\n/g, '<br>');
    document.getElementById('content').innerHTML = '<p>' + html + '</p>';
    setTimeout(() => { window.print(); }, 300);
  </script>
</body>
</html>`)
  win.document.close()
}

function OutputCard({ output, onDelete }: { output: Output; onDelete: (id: string) => void }) {
  const [copied, setCopied] = useState(false)
  const [expanded, setExpanded] = useState(true)

  function copy() {
    void navigator.clipboard.writeText(output.content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const date = new Date(output.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })

  return (
    <div className="bg-slate-900/60 border border-slate-800 rounded-2xl overflow-hidden">
      <div className="flex items-center justify-between px-4 py-3 border-b border-slate-800/60">
        <div className="flex items-center gap-2 min-w-0">
          <FileText className="w-3.5 h-3.5 text-blue-400 flex-shrink-0" />
          <span className="text-sm font-semibold text-slate-200 truncate">{output.title}</span>
        </div>
        <div className="flex items-center gap-1 flex-shrink-0 ml-2">
          <span className="text-[10px] text-slate-600 mr-1 hidden sm:block">{date}</span>
          <button onClick={copy} title="Copy" className="p-1.5 text-slate-600 hover:text-blue-400 transition-colors rounded-lg hover:bg-slate-800">
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
          </button>
          <button onClick={() => printOutput(output.title, output.content)} title="Print / Save as PDF" className="p-1.5 text-slate-600 hover:text-slate-300 transition-colors rounded-lg hover:bg-slate-800">
            <Printer className="w-3.5 h-3.5" />
          </button>
          <button onClick={() => onDelete(output.id)} title="Delete" className="p-1.5 text-slate-600 hover:text-red-400 transition-colors rounded-lg hover:bg-slate-800">
            <Trash2 className="w-3.5 h-3.5" />
          </button>
          <button onClick={() => setExpanded(!expanded)} className="p-1.5 text-slate-600 hover:text-slate-300 transition-colors rounded-lg hover:bg-slate-800">
            {expanded ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
          </button>
        </div>
      </div>
      {expanded ? (
        <div className="px-4 py-4">
          <pre className="text-sm text-slate-300 leading-relaxed whitespace-pre-wrap font-sans">{output.content}</pre>
        </div>
      ) : (
        <div className="px-4 py-2">
          <p className="text-xs text-slate-600 leading-relaxed line-clamp-2">{output.content.slice(0, 140)}…</p>
        </div>
      )}
    </div>
  )
}

export default function OperativeChat({ operative, isPro }: { operative: Operative; isPro: boolean }) {
  const [name, setName] = useState(operative.name)
  const [activeTab, setActiveTab] = useState<'generate' | 'chat'>('generate')
  const [showWizard, setShowWizard] = useState(!operative.memory || operative.memory.trim() === '')

  // Generate state
  const [generatePrompt, setGeneratePrompt] = useState('')
  const [generating, setGenerating] = useState(false)
  const [generateError, setGenerateError] = useState('')
  const [outputs, setOutputs] = useState<Output[]>([])
  const [loadingOutputs, setLoadingOutputs] = useState(true)

  // Chat state
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const [streamingContent, setStreamingContent] = useState('')
  const [chatError, setChatError] = useState('')
  const [showSettings, setShowSettings] = useState(false)
  const [upgradeRequired, setUpgradeRequired] = useState(false)

  const bottomRef = useRef<HTMLDivElement>(null)
  const isCustom = operative.suite_id === 'custom'
  const description = operative.config?.description
  const quickActions = getQuickActions(name, description ?? '')

  useEffect(() => { void loadOutputs() }, [])
  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }) }, [messages, streamingContent])

  async function loadOutputs() {
    setLoadingOutputs(true)
    try {
      const res = await fetch(`/api/operative/${operative.id}/generate`)
      const data = await res.json() as { success: boolean; data: Output[] }
      if (data.success) setOutputs(data.data)
    } finally {
      setLoadingOutputs(false)
    }
  }

  async function generate(prompt?: string) {
    const p = (prompt ?? generatePrompt).trim()
    if (!p || generating) return
    setGenerating(true)
    setGenerateError('')
    if (!prompt) setGeneratePrompt('')

    try {
      const res = await fetch(`/api/operative/${operative.id}/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: p }),
      })
      const data = await res.json() as { success: boolean; data?: Output; error?: string }
      if (!data.success) throw new Error(data.error)
      setOutputs((prev) => [data.data!, ...prev])
    } catch (err) {
      setGenerateError(err instanceof Error ? err.message : 'Failed to generate')
    } finally {
      setGenerating(false)
    }
  }

  async function deleteOutput(outputId: string) {
    setOutputs((prev) => prev.filter((o) => o.id !== outputId))
    await fetch(`/api/operative/${operative.id}/generate?output_id=${outputId}`, { method: 'DELETE' })
  }

  function extractMemoryBackground(completedMessages: Message[]) {
    if (!isCustom || completedMessages.length < 2) return
    fetch(`/api/operative/${operative.id}/memory`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ messages: completedMessages.slice(-4).map((m) => ({ role: m.role, content: m.content })) }),
    }).catch(() => {})
  }

  async function sendMessage(text?: string) {
    const msg = (text ?? input).trim()
    if (!msg || loading) return
    setInput('')
    setChatError('')
    setLoading(true)
    setStreamingContent('')

    const userMsg: Message = { id: crypto.randomUUID(), role: 'user', content: msg }
    const nextMessages = [...messages, userMsg]
    setMessages(nextMessages)

    try {
      const res = await fetch(`/api/operative/${operative.id}/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: nextMessages.map((m) => ({ role: m.role, content: m.content })) }),
      })

      if (res.status === 403) {
        const d = await res.json() as { error: string }
        if (d.error === 'upgrade_required') { setUpgradeRequired(true); setLoading(false); return }
      }
      if (!res.ok) { setChatError(`Error ${res.status}`); setLoading(false); return }

      const reader = res.body!.getReader()
      const decoder = new TextDecoder()
      let buffer = ''
      let fullContent = ''

      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        buffer += decoder.decode(value, { stream: true })
        const lines = buffer.split('\n\n')
        buffer = lines.pop() ?? ''
        for (const line of lines) {
          if (!line.startsWith('data: ')) continue
          const raw = line.slice(6).trim()
          if (!raw) continue
          try {
            const event = JSON.parse(raw) as { type: string; content?: string; message?: string }
            if (event.type === 'text') { fullContent += event.content ?? ''; setStreamingContent(fullContent) }
            else if (event.type === 'done') {
              const assistantMsg: Message = { id: crypto.randomUUID(), role: 'assistant', content: fullContent }
              const finalMessages = [...nextMessages, assistantMsg]
              setMessages(finalMessages)
              setStreamingContent('')
              extractMemoryBackground(finalMessages)
            } else if (event.type === 'error') { setChatError(event.message ?? 'Unknown error') }
          } catch { /* malformed */ }
        }
      }
    } catch { setChatError('Connection error. Please try again.') }
    finally { setLoading(false) }
  }

  if (upgradeRequired) {
    return (
      <div className="min-h-screen bg-[#0a0a0f] text-slate-100 flex flex-col items-center justify-center px-6">
        <div className="max-w-md w-full bg-blue-950/30 border border-blue-800/50 rounded-2xl p-8 text-center space-y-4">
          <div className="w-12 h-12 bg-blue-600/20 border border-blue-600/30 rounded-2xl flex items-center justify-center mx-auto">
            <Cpu className="w-6 h-6 text-blue-400" />
          </div>
          <h2 className="text-xl font-bold">Custom Operatives require Pro</h2>
          <p className="text-slate-400 text-sm leading-relaxed">
            Upgrade to Iron Operative Pro to access custom operatives, the full template library, and the deployment agent.
          </p>
          <UpgradeButton
            label="Upgrade to Pro — $49/mo"
            className="w-full flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-500 text-white py-3 rounded-xl text-sm font-semibold transition-colors"
          />
          <Link href="/dashboard" className="block text-xs text-slate-600 hover:text-slate-400 transition-colors">
            Back to dashboard
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-[#0a0a0f] text-slate-100 flex flex-col">
      {/* Setup wizard — shown on first open if no memory */}
      {showWizard && isCustom && (
        <OperativeWizard
          operativeId={operative.id}
          operativeName={name}
          onComplete={() => setShowWizard(false)}
        />
      )}

      {/* Header */}
      <header className="border-b border-slate-800/60 px-4 sm:px-6 py-4 flex-shrink-0 bg-[#0a0a0f]/95 backdrop-blur sticky top-0 z-10">
        <div className="max-w-5xl mx-auto flex items-center gap-3">
          <Link href="/dashboard" className="text-slate-500 hover:text-slate-300 transition-colors">
            <ArrowLeft className="w-4 h-4" />
          </Link>
          <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center flex-shrink-0">
            <Cpu className="w-4 h-4 text-white" />
          </div>
          <div className="min-w-0 flex-1">
            <span className="font-bold text-base sm:text-lg tracking-tight">{name}</span>
            {description && (
              <span className="text-slate-500 text-xs block leading-none hidden sm:block truncate max-w-xs">{description}</span>
            )}
          </div>
          <div className="flex items-center gap-3 ml-auto">
            <div className="hidden sm:flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
              <span className="text-xs text-slate-500">Active</span>
            </div>
            <button onClick={() => setShowSettings(true)} className="text-slate-500 hover:text-slate-300 transition-colors">
              <Settings className="w-4 h-4" />
            </button>
          </div>
        </div>
      </header>

      {/* Tabs */}
      <div className="border-b border-slate-800/60 bg-[#0a0a0f]">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 flex gap-1 pt-1">
          {(['generate', 'chat'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-2.5 text-sm font-medium capitalize border-b-2 transition-colors ${
                activeTab === tab
                  ? 'border-blue-500 text-white'
                  : 'border-transparent text-slate-500 hover:text-slate-300'
              }`}
            >
              {tab === 'generate' ? 'Generate' : 'Chat'}
            </button>
          ))}
        </div>
      </div>

      {/* Generate tab */}
      {activeTab === 'generate' && (
        <div className="flex-1 max-w-5xl mx-auto w-full px-4 sm:px-6 py-8">
          <div className="mb-8">
            <h2 className="text-lg font-bold mb-1">What do you need?</h2>
            <p className="text-slate-500 text-sm mb-4">Describe the task — your operative delivers a finished, ready-to-use output.</p>

            {/* Quick action chips */}
            <div className="flex flex-wrap gap-2 mb-4">
              {quickActions.map((action) => (
                <button
                  key={action}
                  onClick={() => void generate(action)}
                  disabled={generating}
                  className="text-xs px-3 py-1.5 bg-slate-800/80 hover:bg-slate-700 border border-slate-700/60 hover:border-slate-600 text-slate-400 hover:text-slate-200 rounded-lg transition-all disabled:opacity-40"
                >
                  {action}
                </button>
              ))}
            </div>

            <div className="bg-slate-900 border border-slate-700 rounded-2xl p-3 focus-within:border-blue-700/60 transition-colors">
              <textarea
                value={generatePrompt}
                onChange={(e) => setGeneratePrompt(e.target.value)}
                onKeyDown={(e) => { if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) void generate() }}
                placeholder="Or describe exactly what you need — include customer name, job details, pricing, any specifics…"
                rows={3}
                disabled={generating}
                className="w-full bg-transparent text-slate-100 placeholder-slate-600 text-sm resize-none focus:outline-none leading-relaxed"
              />
              <div className="flex items-center justify-between mt-2">
                <span className="text-xs text-slate-700">⌘+Enter to generate</span>
                <button
                  onClick={() => void generate()}
                  disabled={!generatePrompt.trim() || generating}
                  className="flex items-center gap-2 bg-blue-600 hover:bg-blue-500 disabled:opacity-40 disabled:cursor-not-allowed text-white px-5 py-2 rounded-xl text-sm font-semibold transition-colors"
                >
                  {generating ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Zap className="w-3.5 h-3.5" />}
                  {generating ? 'Generating…' : 'Generate'}
                </button>
              </div>
            </div>
            {generateError && (
              <div className="mt-3 flex items-center gap-2 text-sm text-red-400">
                <AlertCircle className="w-4 h-4" /> {generateError}
              </div>
            )}
          </div>

          {/* Outputs */}
          <div>
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-semibold text-slate-300">
                Deliverables
                {outputs.length > 0 && <span className="ml-2 text-xs text-slate-600 font-normal">{outputs.length} saved</span>}
              </h3>
            </div>

            {loadingOutputs ? (
              <div className="flex items-center gap-2 text-slate-600 text-sm py-8">
                <Loader2 className="w-4 h-4 animate-spin" /> Loading…
              </div>
            ) : outputs.length === 0 ? (
              <div className="border-2 border-dashed border-slate-800 rounded-2xl p-12 text-center">
                <FileText className="w-8 h-8 text-slate-700 mx-auto mb-3" />
                <p className="text-slate-600 text-sm">Generated outputs appear here.</p>
                <p className="text-slate-700 text-xs mt-1">Every deliverable is saved and printable.</p>
              </div>
            ) : (
              <div className="space-y-4">
                {outputs.map((output) => (
                  <OutputCard key={output.id} output={output} onDelete={(id) => void deleteOutput(id)} />
                ))}
              </div>
            )}
          </div>
        </div>
      )}

      {/* Chat tab */}
      {activeTab === 'chat' && (
        <>
          <div className="flex-1 max-w-3xl mx-auto w-full px-4 sm:px-6 py-6 space-y-6">
            {messages.length === 0 && !streamingContent && (
              <div className="pt-16 text-center space-y-4">
                <div className="w-14 h-14 bg-blue-600/20 border border-blue-600/30 rounded-2xl flex items-center justify-center mx-auto">
                  <Cpu className="w-7 h-7 text-blue-400" />
                </div>
                <div>
                  <h1 className="text-2xl font-bold mb-2">{name}</h1>
                  {description && <p className="text-slate-400 text-sm max-w-md mx-auto">{description}</p>}
                </div>
                <p className="text-xs text-slate-600">Use Generate for one-shot deliverables. Use Chat for back-and-forth refinement.</p>
              </div>
            )}

            {messages.map((msg) => (
              <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                {msg.role === 'user' ? (
                  <div className="bg-slate-800 rounded-2xl rounded-tr-sm px-4 py-3 max-w-[80%] text-sm text-slate-100">{msg.content}</div>
                ) : (
                  <div className="flex items-start gap-2.5 max-w-[90%]">
                    <div className="w-7 h-7 bg-blue-600/20 border border-blue-600/30 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5">
                      <Cpu className="w-3.5 h-3.5 text-blue-400" />
                    </div>
                    <div className="bg-slate-900/80 border border-slate-800 rounded-2xl rounded-tl-sm px-4 py-3 text-sm text-slate-200 leading-relaxed whitespace-pre-wrap">
                      {msg.content}
                    </div>
                  </div>
                )}
              </div>
            ))}

            {streamingContent && (
              <div className="flex items-start gap-2.5">
                <div className="w-7 h-7 bg-blue-600/20 border border-blue-600/30 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5">
                  <Cpu className="w-3.5 h-3.5 text-blue-400" />
                </div>
                <div className="bg-slate-900/80 border border-slate-800 rounded-2xl rounded-tl-sm px-4 py-3 text-sm text-slate-200 leading-relaxed whitespace-pre-wrap max-w-[90%]">
                  {streamingContent}
                </div>
              </div>
            )}

            {loading && !streamingContent && (
              <div className="flex items-center gap-2.5">
                <div className="w-7 h-7 bg-blue-600/20 border border-blue-600/30 rounded-lg flex items-center justify-center flex-shrink-0">
                  <Loader2 className="w-3.5 h-3.5 text-blue-400 animate-spin" />
                </div>
                <div className="flex gap-1">
                  <span className="w-1.5 h-1.5 bg-slate-600 rounded-full animate-bounce [animation-delay:0ms]" />
                  <span className="w-1.5 h-1.5 bg-slate-600 rounded-full animate-bounce [animation-delay:150ms]" />
                  <span className="w-1.5 h-1.5 bg-slate-600 rounded-full animate-bounce [animation-delay:300ms]" />
                </div>
              </div>
            )}

            {chatError && (
              <div className="flex items-start gap-2 bg-red-950/40 border border-red-800/50 rounded-xl px-4 py-3 text-sm text-red-300">
                <AlertCircle className="w-4 h-4 flex-shrink-0 mt-0.5" />{chatError}
              </div>
            )}
            <div ref={bottomRef} />
          </div>

          <div className="sticky bottom-0 bg-[#0a0a0f]/95 backdrop-blur border-t border-slate-800/60 px-4 sm:px-6 py-4">
            <div className="max-w-3xl mx-auto">
              <div className="bg-slate-900 border border-slate-700 rounded-2xl p-3 focus-within:border-blue-700/60 transition-colors">
                <textarea
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => { if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) { e.preventDefault(); void sendMessage() } }}
                  placeholder={`Tell ${name} what you need…`}
                  rows={2}
                  disabled={loading}
                  className="w-full bg-transparent text-slate-100 placeholder-slate-600 text-sm resize-none focus:outline-none leading-relaxed"
                />
                <div className="flex items-center justify-between mt-2">
                  <span className="text-xs text-slate-700">⌘+Enter to send</span>
                  <button
                    onClick={() => void sendMessage()}
                    disabled={!input.trim() || loading}
                    className="flex items-center gap-2 bg-blue-600 hover:bg-blue-500 disabled:opacity-40 disabled:cursor-not-allowed text-white px-4 py-2 rounded-xl text-sm font-semibold transition-colors"
                  >
                    {loading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Send className="w-3.5 h-3.5" />}
                    {loading ? 'Working…' : 'Send'}
                  </button>
                </div>
              </div>
            </div>
          </div>
        </>
      )}

      {showSettings && (
        <OperativeSettings
          operativeId={operative.id}
          operativeName={name}
          onClose={() => setShowSettings(false)}
          onRenamed={(newName) => setName(newName)}
        />
      )}
    </div>
  )
}
