import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0f] text-slate-100">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-slate-300 text-sm mb-10 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back
        </Link>

        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: June 2025</p>

        <div className="prose prose-invert prose-slate max-w-none space-y-8 text-slate-300 text-sm leading-relaxed">

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using Iron Operative ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Platform.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
            <p>Iron Operative is an AI-powered business automation platform that allows users to deploy AI operative agents ("Operatives") to assist with business tasks including but not limited to generating quotes, proposals, emails, and other business documents.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. AI-Generated Content Disclaimer</h2>
            <p>All content generated by Iron Operative's AI operatives is provided for informational and reference purposes only. AI-generated outputs — including quotes, proposals, emails, contracts, and other documents — are not professional legal, financial, or business advice.</p>
            <p className="mt-3">You are solely responsible for reviewing, verifying, and approving all AI-generated content before use. Iron Operative makes no representations or warranties regarding the accuracy, completeness, or suitability of any AI-generated output. Iron Operative shall not be liable for any losses, damages, or claims arising from reliance on AI-generated content.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. User Responsibilities</h2>
            <p>You agree to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Use the Platform only for lawful business purposes</li>
              <li>Review all AI-generated content before sending to third parties</li>
              <li>Not use the Platform to generate misleading, fraudulent, or harmful content</li>
              <li>Maintain the security of your account credentials</li>
              <li>Comply with all applicable laws and regulations in your jurisdiction</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. Subscription and Billing</h2>
            <p>Iron Operative offers free and paid subscription tiers. Paid subscriptions are billed monthly through Stripe. You may cancel at any time; cancellation takes effect at the end of the current billing period. No refunds are issued for partial months.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. Intellectual Property</h2>
            <p>You retain ownership of content you input into the Platform. AI-generated outputs produced using your inputs are owned by you. Iron Operative retains all rights to the Platform, its software, design, and underlying technology.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, Iron Operative shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Platform or reliance on AI-generated content. Our total liability shall not exceed the amount you paid in the 30 days prior to the claim.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Termination</h2>
            <p>Iron Operative reserves the right to suspend or terminate accounts that violate these Terms or are used in a manner that could cause harm to the Platform or other users.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. Changes to Terms</h2>
            <p>We may update these Terms at any time. Continued use of the Platform after changes constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">10. Contact</h2>
            <p>Questions about these Terms? Contact us at <a href="mailto:support@ironoperative.com" className="text-blue-400 hover:text-blue-300">support@ironoperative.com</a>.</p>
          </section>

        </div>
      </div>
    </div>
  )
}
